### ISSUE TITLE
 Instructions on how to disable vsync not available

### ISSUE THREAD

**Issue by HealerLFG** [linkthehylian/UNOTweaks#1]
ReadMe states that you may toggle vsync and set preferred FPS using tool, but provides no instructions on how to make those changes.  No launcher, splash, or overlay are added and no visible toggle is added to the in-game settings.

**Comment by linkthehylian** [comment]
Everything I've added for these tweaks immediately get shown once you're on the main menu. If they somehow don't, you can press F1 to show the main window that will provide them.

Due to how Ubisoft integrated their in-game settings I wasn't able to add my tweaks alongside them.
![UNO_hojC8AfpJD](https://user-images.githubusercontent.com/20933012/180174668-39affa04-c0fc-4c5a-8f14-ccbfbb30da01.png)

Hoping this helps. Apologies for the README not being clear, I'll have it updated asap.

**Comment by HealerLFG** [comment]
Yeah, that overlay definitely doesn't show up for me on launch, but pressing F1 indeed pulls it up.
